version: 0.1
http:
  addr: :5000
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key
  headers:
    X-Content-Type-Options: [nosniff]

auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd

storage:
  filesystem:
    rootdirectory: /var/lib/registry

